import{a as y,S as g,i as c}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const h="53360478-1bf245edf032d22b013a2c514",L="https://pixabay.com/api/";function b(r){if(!r)return Promise.resolve(null);const o=L+`?key=${h}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true`;return y.get(o).then(function(n){return n.data})}const u=document.querySelector(".form"),a=document.querySelector(".js-gallery");function f(){a&&(a.innerHTML="")}const w=()=>document.body&&document.body.classList.add("is-loading"),v=()=>document.body&&document.body.classList.remove("is-loading"),l=new g(".gallery a",{captionsData:"alt",captionDelay:250});function S(r){if(!Array.isArray(r)||!a){f();return}const o=r.map(n=>{const{largeImageURL:s="#",webformatURL:e="",tags:t="",likes:i=0,views:m=0,comments:d=0,downloads:p=0}=n||{};return`
      <li class="gallery-item">
        <a class="gallery-link js-gallery-link" href="${s}">
          <img class="gallery-image" src="${e}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><span>Likes:</span> ${i}</p>
          <p class="info-item"><span>Views:</span> ${m}</p>
          <p class="info-item"><span>Comments:</span> ${d}</p>
          <p class="info-item"><span>Downloads:</span> ${p}</p>
        </div>
      </li>`}).join("");a.innerHTML=o,l&&typeof l.refresh=="function"&&l.refresh()}u?u.addEventListener("submit",$):console.warn("Search form not found (.form)");function $(r){r.preventDefault();const n=r.currentTarget.elements["search-text"],s=(n&&n.value||"").trim();if(!s){c.warning({message:"Поле не должно быть пустым"});return}w(),b(s).then(function(e){if(!e||!Array.isArray(e.hits)||e.hits.length===0){f(),c.info({message:"По вашему запросу ничего не найдено."});return}S(e.hits)}).catch(function(e){f(),c.error({message:"Произошла ошибка при загрузке результатов."}),console.error(e)}).finally(function(){v()})}
//# sourceMappingURL=index.js.map
